services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-app
    volumes:
      - ./:/var/www/html
      - ./php/config/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - db
    networks:
      - backend
    env_file:
      - .env

  db:
    image: postgres:15-alpine
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2328
      POSTGRES_DB: framework
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    networks:
      - backend

  nginx:
    image: nginx:latest
    container_name: nginx-server
    ports:
      - 8080:80
    volumes:
      - ./public:/var/www/html/public
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - backend


networks:
  backend:
    driver: bridge